### ISSUE TITLE
Created files should be ignored

### ISSUE THREAD

**Issue by mcollina** [andreareginato/conference_site#4] opened 2012-01-12 17:37 UTC
In order to support a multi-developer build, I think the built html files should not be checked in to the source code tree.

**Comment by andreareginato** [comment] 2012-01-14 15:15
Tell me more about your point of view. I don't get it totally :)

**Comment by mcollina** [comment] 2012-01-14 18:20
In C, do you put your binaries in source code?
So, why would you want to do that with html? :D

Ideally these files should be generated, however I think you can't do that and deploy on Heroku.
So, it's not an issue for this project :/.

**Comment by andreaforni** [comment] 2012-01-20 11:01
Hi,
I agree with Matteo, the files inside the "public" and "tmp" directories should not be included in git. We can create (and re-create) their contents using nanoc. In addition, I think the commits would be clearer because they would include only the modified files and not the generated ones.

If the "public" and "tmp" directories are necessary for the deploy to Heroku, the only thing that comes to my mind is to:
1. remove "public" and "tmp" contents from the "master" (adding them to gitignore), so who branch from master does not commits the generated files;
2. create a "deploy branch", for example named "to_heroku" or something similar, where "public" and "tmp" contents are managed with git. In this branch we can merge the changes to push to Heroku.

But the project is so simple that we can continue to work with "public" and "tmp" contents inside git.

My 2 cents...
Andrea

**Comment by mcollina** [comment] 2012-01-20 11:17
+1

**Comment by andreareginato** [comment] 2012-01-25 08:24
So guys. I totally agree with you, but I've one question due to my limited knowledge to git. If I've a "deploy" branch and I merge from master, when I merge, also the .gitignore will be merged. In this case public and tmp dirs will not be considered again. If I'm missing some points just let me know. I would love to make this working.

**Comment by andreaforni** [comment] 2012-01-25 08:51
You are right, this is tricky. We have to find a way to tell to git to merge all files except the ".gitignore". I tried to add ".gitignore" entry into ".gitignore" file but it didn't work :-) I'll try to find something...

**Comment by mcollina** [comment] 2012-01-25 08:54
After the merge, in the deploy branch you can change and commit a .gitignore without the public/ and tmp/ dirs, generate everything and commit the whole package.

**Comment by andreareginato** [comment] 2012-01-25 08:58
This is a working solution but I've the feeling there is a much more neat solution. I'll try to search about.

**Comment by elia** [comment] 2012-02-17 11:06
The best thing can be to configure `nanoc` to output in `tmp` and `rack` to get static files from there too…

(do we really need to write in english?)

**Comment by elia** [comment] 2012-02-17 11:18
we can also deploy on say gh-pages (under the (rubyday org)[https://github.com/rubyday]) and simply have a deploy rake task (it's completely static right?)

**Comment by andreaforni** [comment] 2012-02-17 11:25
Also the `tmp` directory is inside the github repository. The problem is the same: we would like to trace it in the `deploy` branch (to push it to Heroku) but not in the `master` branch. 

I'm missing something?

(Uhm I don't know... The `readme`, the website and all the issues (except one) are in english... Just to be more "international" :-D)

**Comment by elia** [comment] 2012-02-17 11:34
Of course the tmp shouldn't be in the repo, no matter the branch, tmp in heroku is writable, so that solution should work, not sure about gh-pages…

**Comment by mcollina** [comment] 2012-02-17 11:38
Everything is writable with Heroku, but it's volatile as it's flushed at
every restart.

I'm not finding a way to easily compile things at every restart.

**Comment by elia** [comment] 2012-02-17 11:39
we probably need something like assets:precompile…

**Comment by andreaforni** [comment] 2012-02-17 11:41
Ok, but I think (but I'm not sure because Andrea is the one who push to Heroku) we run `nanoc` locally, it generates the static pages, these pages are commited and then pushed to github and pushed to Heroku. We do not push the source file and then run `nanoc` on Heroku to generate them.

**Comment by elia** [comment] 2012-02-17 11:44
Hence is what we should do :)
- remove both public and tmp from repo
- deploy only the source
- run a rake-ish nanoc command to get the files after each deploy 

(as @mcollina said if we're on cedar the whole app dir is writable)

**Comment by mcollina** [comment] 2012-02-17 12:23
Il giorno 17 febbraio 2012 12:44, Elia Schito <
reply@reply.github.com

> ha scritto:
> 
> Hence is what we should do :)
> - remove both public and tmp from repo
> - deploy only the source
> - run a rake-ish nanoc command to get the files after each deploy

yeah, but I still don't know how to do the last point :D

**Comment by elia** [comment] 2012-02-17 12:35
@mcollina it's probably `heroku run nanoc3 compile`

**Comment by mcollina** [comment] 2012-02-17 12:40
Actually no, because each process has its own volatile space :/.
So you generate them there, but they can't be seen by the web process.

**Closed as completed** 2012-02-17 13:05 UTC
